apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-fe
  annotations:
    mia-platform.eu/version: 14.3.1
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    fluentbit.io/parser: nginx
  labels:
    app: agent-fe
    app.kubernetes.io/name: agent-fe
    app.kubernetes.io/version: 1.1.11
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: compatibility-test-dp
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
    mia-platform.eu/log-type: mia-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-fe
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        fluentbit.io/parser: nginx
      labels:
        app: agent-fe
        app.kubernetes.io/name: agent-fe
        app.kubernetes.io/version: 1.1.11
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: compatibility-test-dp
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: DEV
        mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
        mia-platform.eu/log-type: mia-nginx
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
        - name: orca-ghcr
        - name: orca-google-registry
      terminationGracePeriodSeconds: 30
      serviceAccountName: agent-fe
      containers:
        - name: agent-fe
          image: nexus.mia-platform.eu/hub/hub-fe:1.1.11
          imagePullPolicy: Always
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 50m
          volumeMounts:
            - name: hub-fe-configuration
              mountPath: /usr/static/hub-fe-config.json
              readOnly: true
              subPath: hub-fe-config.json
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args: []
          env:
            - name: HTTP_PORT
              value: '8080'
            - name: LOG_LEVEL
              value: 'debug'
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/healthz
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes:
        - name: hub-fe-configuration
          configMap:
            name: hub-fe-configuration
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
