apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-bff
  annotations:
    mia-platform.eu/version: 14.3.1
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    fluentbit.io/parser: pino
  labels:
    app: agent-bff
    app.kubernetes.io/name: agent-bff
    app.kubernetes.io/version: 1.1.1
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: compatibility-test-dp
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
    mia-platform.eu/log-type: mia-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-bff
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        fluentbit.io/parser: pino
      labels:
        app: agent-bff
        app.kubernetes.io/name: agent-bff
        app.kubernetes.io/version: 1.1.1
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: compatibility-test-dp
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: DEV
        mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
        mia-platform.eu/log-type: mia-json
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
        - name: orca-ghcr
        - name: orca-google-registry
      terminationGracePeriodSeconds: 30
      serviceAccountName: agent-bff
      containers:
        - name: agent-bff
          image: nexus.mia-platform.eu/hub/hub-bff:1.1.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 50m
          volumeMounts: []
          ports:
            - name: http
              containerPort: 3000
          args: []
          env:
            - name: LOG_LEVEL
              value: 'debug'
            - name: MICROSERVICE_GATEWAY_SERVICE_NAME
              value: microservice-gateway
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: HTTP_PORT
              value: '3000'
            - name: USERID_HEADER_KEY
              value: miauserid
            - name: GROUPS_HEADER_KEY
              value: miausergroups
            - name: CLIENTTYPE_HEADER_KEY
              value: client-type
            - name: BACKOFFICE_HEADER_KEY
              value: isbackoffice
            - name: USER_PROPERTIES_HEADER_KEY
              value: miauserproperties
            - name: CONVERSATIONS_CRUD_BASE_URL
              value: http://crud-service
            - name: CONVERSATIONS_CRUD_NAME
              value: conversations
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /status/alive
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /status/alive
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes: []
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
