apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-service
  annotations:
    mia-platform.eu/version: 14.3.1
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    fluentbit.io/parser: pino
  labels:
    app: crud-service
    app.kubernetes.io/name: crud-service
    app.kubernetes.io/version: 7.2.3
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: compatibility-test-dp
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
    mia-platform.eu/log-type: mia-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-service
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        fluentbit.io/parser: pino
      labels:
        app: crud-service
        app.kubernetes.io/name: crud-service
        app.kubernetes.io/version: 7.2.3
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: compatibility-test-dp
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: DEV
        mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
        mia-platform.eu/log-type: mia-json
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
        - name: orca-ghcr
        - name: orca-google-registry
      terminationGracePeriodSeconds: 30
      serviceAccountName: crud-service
      containers:
        - name: crud-service
          image: nexus.mia-platform.eu/core/crud-service:7.2.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: 200Mi
              cpu: 300m
            requests:
              memory: 50Mi
              cpu: 70m
          volumeMounts:
            - name: crud-service-collections
              mountPath: /home/node/app/collections
              readOnly: true
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          args: []
          env:
            - name: LOG_LEVEL
              value: 'debug'
            - name: HTTP_PORT
              value: '3000'
            - name: COLLECTION_DEFINITION_FOLDER
              value: /home/node/app/collections
            - name: USER_ID_HEADER_KEY
              value: miauserid
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: CRUD_LIMIT_CONSTRAINT_ENABLED
              value: '{{CRUD_LIMIT_CONSTRAINT_ENABLED}}'
            - name: EXPOSE_METRICS
              value: 'false'
            - name: MONGODB_URL
              value: '{{MONGODB_URL}}'
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/healthz
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes:
        - name: crud-service-collections
          configMap:
            name: crud-service-collections
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
