apiVersion: v1
kind: Service
metadata:
  name: crud-service
  annotations:
    mia-platform.eu/version: 14.3.1
  labels:
    app: crud-service
    app.kubernetes.io/name: crud-service
    app.kubernetes.io/version: 7.2.3
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: compatibility-test-dp
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: null
  selector:
    app: crud-service
